user www;
worker_processes  %%WORKER_PROCESSES%%;

#  По умолчанию nginx вызывает gettimeofday() очень часто. Уменьшение разрешения таймера снизит количество системных вызовов.
timer_resolution 100ms;

error_log       /dev/null;
pid             /var/run/nginx.pid;

events {
	use kqueue;
	worker_connections  1024;
	kqueue_changes  2048;

	accept_mutex off;        # Обязательно OFF для одного ядра и reuseport
#	accept_mutex on;        # Обязательно OFF для одного ядра и reuseport
#	multi_accept on; # Заставляет воркер забирать все соединения из очереди за один вызов
}

http {
	server_tokens off;
	include       mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for"';

	etag off;

	access_log                      /dev/null;
	error_log                       /dev/null;

	client_body_buffer_size         32K;
	client_body_timeout             3m;
	client_header_buffer_size       1k;
	client_header_timeout           3m;
	client_max_body_size            20m;
	gzip                            off;
	large_client_header_buffers     4 8k;
	output_buffers                  1 32k;

	reset_timedout_connection       on;
	send_timeout                    3m;

	tcp_nodelay                     on;
	tcp_nopush                      on;

	keepalive_timeout 65;
	keepalive_requests 100000; # Разрешить прокачивать много запросов через один сокет

	# Позволяет nginx быстрее закрывать сокеты, не дожидаясь лишних данных от клиента.
	lingering_close off;

server {
	listen 127.0.0.1:8080 default_server reuseport;

	error_log /dev/null;
	access_log off;

	server_name _;

	location = /index.html {
		default_type text/html;
		return 200 'OK';
		}
	}
}
