if [ ! "$_BENCH_SUBR" ]; then
_BENCH_SUBR=1
###

# fatal error. Print message to stdout then quit with exitval
err() {
	exitval=$1
	shift
	echo "$*" 1>&2
	exit ${exitval}
}

mini_stat()
{
	local _ministat_args= i=

	_ministat_args="-s -w 74"

	for i in ${RUN_CORES_RANGE}; do
		${progdir}/parselog-ministat.sh-alldata output/${PLATFORM}-${i}.log > output/ministat-${i}.log
		${progdir}/parselog-ministat.sh-average output/${PLATFORM}-${i}.log | tee -a output/ministat-${i}.log.avg
		_ministat_args="${_ministat_args} output/ministat-${i}.log"
	done

	if [ -z "${QUIET}" -a -n "${MINISTAT_CMD}" ]; then
		set -o xtrace
		${MINISTAT_CMD} ${_ministat_args} 1>&2
		set +o xtrace
	fi

	return 0
}


PLATFORM=$( uname -s )
CORES_ALL=$( nproc )
MINISTAT_CMD=

case ${PLATFORM} in
	Linux)
		AWK_CMD="awk"
		;;
	FreeBSD)
		AWK_CMD="gawk"
		MINISTAT_CMD=$( command -v "ministat" 2>/dev/null )
		;;
esac

###
fi
