#!/bin/sh
progdir="${0%/*}"
[ "$progdir" = "$0" ] && progdir="."
progdir=$(cd "$progdir" && pwd -P)

set -e
. ${progdir}/bench.subr
set +e


freebsd()
{
	${progdir}/lab1/${PLATFORM}/scripts/sysctl.sh

	for i in nginx gmake libepoll-shim gawk; do
		pkg info ${i} >/dev/null 2>&1 || pkg install -y ${i}
	done

	service nginx enable

	if [ ! -x /usr/local/bin/h1load ]; then
		gmake SSL_LFLAGS="-lssl -lcrypto -lepoll-shim -L/usr/local/lib" INC_CFLAGS="-I/usr/local/include/libepoll-shim" -C ${progdir}/h1load
		install -m 0755 ${progdir}/h1load/h1load /usr/local/bin/h1load
		rm -f ${progdir}/h1load/h1load ${progdir}/h1load/h1load.o
	fi
}

linux()
{
	for i in nginx build-essential libssl-dev; do
		dpkg -s ${i} >/dev/null 2>&1 || apt-get install -y ${i}
	done

	# Включаем и сразу запускаем nginx
	systemctl enable --now nginx

	# Собираем и устанавливаем h1load
	if [ ! -x /usr/local/bin/h1load ]; then
		make -C ${progdir}/h1load
		# В Linux флаг -m задает права, -s можно добавить для strip (очистки от отладочных символов)
		install -m 0755 ${progdir}/h1load/h1load /usr/local/bin/h1load
		# Очистка после сборки (в Linux make обычно поддерживает цель clean)
		make -C ${progdir}/h1load clean || rm -f ${progdir}/h1load/h1load ${progdir}/h1load/*.o
	fi
}

case "${PLATFORM}" in
	FreeBSD)
		freebsd
		;;
	Linux)
		linux
		;;
esac
