#!/bin/sh
progdir="${0%/*}"
[ "$progdir" = "$0" ] && progdir="."
progdir=$(cd "$progdir" && pwd -P)

set -e
. ${progdir}/bench.subr
set +e

[ -d ${progdir}/output ] && rm -rf ${progdir}/output
mkdir ${progdir}/output

init_cpuset_params()
{
	case ${CORES} in
		1)
			nginx_cpu=0
			h1load_cpu=4
			;;
		2)
			nginx_cpu="0-1"
			h1load_cpu="4-5"
			;;
		3)
			nginx_cpu="0-2"
			h1load_cpu="4-6"
			;;
		4)
			nginx_cpu="0-3"
			h1load_cpu="4-7"
			;;
	esac
}

case "${PLATFORM}" in
	FreeBSD)
		for CORES in 1 2 3 4; do
			echo "** CORES: ${CORES}"
			sed "s/%%WORKER_PROCESSES%%/${CORES}/g" ${progdir}/lab1/${PLATFORM}/etc/nginx/nginx.conf > /usr/local/etc/nginx/nginx.conf
			concurrent=$(( 100 * CORES ))

			init_cpuset_params

			# NGINX запускаем на ядрах в диапазоне 0-3, HLOAD - 4-7
			service nginx restart
			for pid in $(pgrep nginx); do
				cpuset -l ${nginx_cpu} -p ${pid}
			done
			sleep 1

			# Запускаем h1load на ядрах 4-8
			cpuset -l ${h1load_cpu} h1load -d 60 -t ${CORES} -c ${concurrent} -r 5000 -P -S -l -A http://127.0.0.1:8080/index.html | tee -a  output/${PLATFORM}-${CORES}.log
			sleep 5
		done
		;;
	Linux)
		for CORES in 1 2 3 4; do
			echo "** CORES: ${CORES}"
			# Путь к конфигу в Debian обычно /etc/nginx/nginx.conf
			sed "s/%%WORKER_PROCESSES%%/${CORES}/g" ${progdir}/lab1/${PLATFORM}/etc/nginx/nginx.conf > /etc/nginx/nginx.conf
			concurrent=$(( 100 * CORES ))

			init_cpuset_params
			# NGINX запускаем на ядрах в диапазоне 0-3, HLOAD - 4-7
			systemctl restart nginx
			for pid in $(pgrep nginx); do
				taskset -pc ${nginx_cpu} ${pid} > /dev/null
			done
			sleep 1

			# Запускаем h1load на ядрах 4-7
			taskset -c ${h1load_cpu} h1load -d 60 -t ${CORES} -c ${concurrent} -r 5000 -P -S -l -A http://127.0.0.1:8080/index.html | tee -a output/${PLATFORM}-${CORES}.log
			sleep 5
		done
		;;
esac

# GNUPLOT
#${AWK_CMD} '/pctl/ {out=1; next} out {if (/^$/ || /^#/) out=0; else print}' output.log > latency.dat
#echo "gnuplot plot_latency.gp"
